---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  cache = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# pollagg

<!-- badges: start -->
<!-- badges: end -->

`pollagg` is a tool for researchers who want to understand trends in public opinion from many noisy polls or surveys.

## Installation

You can install the development version of `pollagg` with

``` r
devtools::install_github("alexpavlakis/pollagg")
```
# Examples



```{r obama_mccain_data}
library(pollagg)
suppressMessages(library(dplyr))
library(ggplot2)

options(mc.cores = parallel::detectCores())
rstan::rstan_options(auto_write = TRUE)

# General election polls - Obama vs McCain 2008
head(obama_mccain_polls)
```

```{r obama_mccain_model, results = F}

y <- select(obama_mccain_polls, `McCain (R)`, `Obama (D)`)
n <- obama_mccain_polls$n
poll_dates <- obama_mccain_polls$poll_end

fit_polls <- yapa(y = y, n = n, poll_dates = poll_dates)

```

```{r obama_mccain_res}

plot(fit_polls, size = 0.8) + 
  ylim(0.3, 0.7) +
  scale_x_date(date_breaks = '1 month') +
  scale_fill_manual(values = c('red', 'blue')) +
  scale_color_manual(values = c('red', 'blue')) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.subtitle = element_text(size = 9),
        legend.position = 'bottom') +
  labs(x = NULL, y = NULL, title = 'General Election: McCain vs. Obama',
       subtitle = 'polls (faint dots), modeled polls (bold dots), trend (line), and trend uncertainty (faded ribbon)', col = NULL, fill = NULL)

```


```{r gss_data}
head(grass_gss)
```

```{r gss_model, results = F}
y <- select(grass_gss, legal, illegal)
n <- grass_gss$n
poll_dates <- grass_gss$year

fit_gss <- yapa(y = y, n = n, poll_dates = poll_dates)

```

```{r gss_res}

plot(fit_gss) + 
  ylim(0, 1) +
  scale_fill_manual(values = c('darkgrey', 'darkgreen')) +
  scale_color_manual(values = c('darkgrey', 'darkgreen')) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.subtitle = element_text(size = 9),
        legend.position = 'bottom') +
  labs(x = NULL, y = NULL, title = 'Should marijuana be made legal?',
       subtitle = 'survey results (faint dots), modeled survey results (bold dots), trend (line), and trend uncertainty (faded ribbon)', col = NULL, fill = NULL)

```



# Model

$$
\begin{align}
y_{p, o} &\sim Binomial(n_p, \theta_{p, o}) \\
\theta_{p, o} &\sim Normal(\mu_{d(p), o}, \sigma^\theta) \\
\mu_{d, o} &= \sum_{t < d} \delta_{t, o} + \alpha_o \\
\delta_{d, o} &\sim Normal(\delta_{d-1, o}, \sigma^\delta)
\end{align}
$$
